version: '2.4'

services:
    rancid:
        image: 'samburney/rancid:latest'
        build: '.'
        restart: 'unless-stopped'
        environment:
            TZ: 'Australia/Adelaide'
            HOME: '/var/rancid'
        volumes:
            - './data/rancid/rancid.conf:/etc/rancid/rancid.conf:ro'
            - './data/rancid/crontab:/var/spool/cron/crontabs/rancid:ro'
            - './data/rancid/msmtprc:/etc/msmtprc:ro'
            - './data/rancid/aliases:/etc/aliases:ro'
            - './data/rancid/backups:/var/rancid'
            - './data/rancid/logs:/var/log/rancid'
